Reverted "Fix 'AttributeError: 'numpy.float64' object has no attribute 'value'".
Because of a959defeac9ada9d96eb6bbfab643217ddb9f035 [formerly ba2241f130ddad376f163c8606bd075500a07ddb]


Former-commit-id: a556694f135f2e556c0756b14f777e9940b1d9f5